package core

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestEncodeEvent(t *testing.T) {
	event := AgUiEvent{
		"type":    AgUiRunStarted,
		"threadId": "t-1",
		"runId":   "r-1",
	}
	encoded := EncodeEvent(event)

	if !strings.HasPrefix(encoded, "event: RUN_STARTED\ndata: ") {
		t.Errorf("expected SSE format prefix, got: %s", encoded)
	}
	if !strings.HasSuffix(encoded, "\n\n") {
		t.Errorf("expected SSE format to end with double newline, got: %s", encoded)
	}

	// Extract the JSON data portion
	lines := strings.SplitN(encoded, "\n", 3)
	if len(lines) < 2 {
		t.Fatalf("expected at least 2 lines, got %d", len(lines))
	}
	dataLine := strings.TrimPrefix(lines[1], "data: ")
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(dataLine), &parsed); err != nil {
		t.Fatalf("data line is not valid JSON: %v", err)
	}
	if parsed["type"] != AgUiRunStarted {
		t.Errorf("expected type RUN_STARTED, got %v", parsed["type"])
	}
	if parsed["threadId"] != "t-1" {
		t.Errorf("expected threadId t-1, got %v", parsed["threadId"])
	}
}

func TestEncodeEvent_EmptyType(t *testing.T) {
	event := AgUiEvent{"foo": "bar"}
	encoded := EncodeEvent(event)
	if !strings.HasPrefix(encoded, "event: \ndata: ") {
		t.Errorf("expected empty event type, got: %s", encoded)
	}
}

func TestEncodeEvents(t *testing.T) {
	events := []AgUiEvent{
		{"type": AgUiRunStarted, "threadId": "t-1"},
		{"type": AgUiRunFinished, "threadId": "t-1"},
	}
	encoded := EncodeEvents(events)

	parts := strings.Split(encoded, "event: ")
	// First element is empty string before first "event: "
	if len(parts) != 3 {
		t.Errorf("expected 3 parts (empty + 2 events), got %d", len(parts))
	}
	if !strings.Contains(parts[1], "RUN_STARTED") {
		t.Errorf("first event should be RUN_STARTED")
	}
	if !strings.Contains(parts[2], "RUN_FINISHED") {
		t.Errorf("second event should be RUN_FINISHED")
	}
}

func TestEncodeEvents_Empty(t *testing.T) {
	encoded := EncodeEvents(nil)
	if encoded != "" {
		t.Errorf("expected empty string for nil events, got: %s", encoded)
	}
}

func TestCreateAgUiEmitter_CustomIDs(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{
		ThreadID: "custom-thread",
		RunID:    "custom-run",
	})

	if emitter.ThreadID() != "custom-thread" {
		t.Errorf("expected custom-thread, got %s", emitter.ThreadID())
	}
	if emitter.RunID() != "custom-run" {
		t.Errorf("expected custom-run, got %s", emitter.RunID())
	}
}

func TestCreateAgUiEmitter_AutoGeneratedIDs(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{})

	if emitter.ThreadID() == "" {
		t.Error("expected auto-generated thread ID, got empty")
	}
	if emitter.RunID() == "" {
		t.Error("expected auto-generated run ID, got empty")
	}
	if emitter.ThreadID() == emitter.RunID() {
		t.Error("thread ID and run ID should be different")
	}
	// UUID format: 8-4-4-4-12 hex chars
	if len(strings.Split(emitter.ThreadID(), "-")) < 5 {
		t.Errorf("thread ID doesn't look like a UUID: %s", emitter.ThreadID())
	}
}

func TestEmitter_RunStarted(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunStarted("")
	if len(chunks) != 1 {
		t.Fatalf("expected 1 chunk, got %d", len(chunks))
	}
	if !strings.Contains(chunks[0], "RUN_STARTED") {
		t.Errorf("expected RUN_STARTED event")
	}
	if !strings.Contains(chunks[0], `"threadId"`) {
		t.Errorf("expected threadId field")
	}
}

func TestEmitter_RunStartedWithParent(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunStarted("parent-run")
	if !strings.Contains(chunks[0], "parent-run") {
		t.Errorf("expected parentRunId in event")
	}
}

func TestEmitter_RunFinished(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunFinished(map[string]string{"status": "ok"})
	if len(chunks) != 1 {
		t.Fatalf("expected 1 chunk, got %d", len(chunks))
	}
	if !strings.Contains(chunks[0], "RUN_FINISHED") {
		t.Errorf("expected RUN_FINISHED event")
	}
	if !strings.Contains(chunks[0], `"result"`) {
		t.Errorf("expected result field")
	}
}

func TestEmitter_RunFinishedNoResult(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunFinished(nil)
	if strings.Contains(chunks[0], `"result"`) {
		t.Errorf("expected no result field when nil")
	}
}

func TestEmitter_RunError(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunError("something broke", "ERR_500")
	if len(chunks) != 1 {
		t.Fatalf("expected 1 chunk, got %d", len(chunks))
	}
	if !strings.Contains(chunks[0], "RUN_ERROR") {
		t.Errorf("expected RUN_ERROR event")
	}
	if !strings.Contains(chunks[0], "something broke") {
		t.Errorf("expected error message in event")
	}
	if !strings.Contains(chunks[0], "ERR_500") {
		t.Errorf("expected error code in event")
	}
}

func TestEmitter_RunErrorNoCode(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.RunError("oops", "")
	if strings.Contains(chunks[0], `"code"`) {
		t.Errorf("expected no code field when empty")
	}
}

func TestEmitter_TextStartDeltaEnd(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	msgID := emitter.TextStart("", "")
	if msgID == "" {
		t.Error("expected auto-generated message ID")
	}

	// Default role is assistant
	if !strings.Contains(chunks[0], `"assistant"`) {
		t.Errorf("expected default role 'assistant'")
	}
	if !strings.Contains(chunks[0], "TEXT_MESSAGE_START") {
		t.Errorf("expected TEXT_MESSAGE_START event")
	}

	emitter.TextDelta("hello ", "")
	if !strings.Contains(chunks[1], "TEXT_MESSAGE_CONTENT") {
		t.Errorf("expected TEXT_MESSAGE_CONTENT event")
	}
	if !strings.Contains(chunks[1], "hello ") {
		t.Errorf("expected delta text")
	}

	emitter.TextEnd("")
	if !strings.Contains(chunks[2], "TEXT_MESSAGE_END") {
		t.Errorf("expected TEXT_MESSAGE_END event")
	}
}

func TestEmitter_TextStartCustomRole(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.TextStart("user", "msg-123")
	if !strings.Contains(chunks[0], `"user"`) {
		t.Errorf("expected custom role 'user'")
	}
	if !strings.Contains(chunks[0], "msg-123") {
		t.Errorf("expected custom message ID")
	}
}

func TestEmitter_TextDeltaPanicsWithoutStart(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	defer func() {
		r := recover()
		if r == nil {
			t.Error("expected panic when calling TextDelta without TextStart")
		}
	}()
	emitter.TextDelta("hello", "")
}

func TestEmitter_TextEndPanicsWithoutStart(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	defer func() {
		r := recover()
		if r == nil {
			t.Error("expected panic when calling TextEnd without TextStart")
		}
	}()
	emitter.TextEnd("")
}

func TestEmitter_TextMessage(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	msgID := emitter.TextMessage("Hello world", "")
	if msgID == "" {
		t.Error("expected auto-generated message ID")
	}
	if len(chunks) != 3 {
		t.Fatalf("expected 3 chunks (start+content+end), got %d", len(chunks))
	}
	if !strings.Contains(chunks[0], "TEXT_MESSAGE_START") {
		t.Errorf("expected TEXT_MESSAGE_START")
	}
	if !strings.Contains(chunks[1], "TEXT_MESSAGE_CONTENT") {
		t.Errorf("expected TEXT_MESSAGE_CONTENT")
	}
	if !strings.Contains(chunks[1], "Hello world") {
		t.Errorf("expected text content")
	}
	if !strings.Contains(chunks[2], "TEXT_MESSAGE_END") {
		t.Errorf("expected TEXT_MESSAGE_END")
	}
}

func TestEmitter_TextMessageCustomRole(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.TextMessage("Hi", "system")
	if !strings.Contains(chunks[0], `"system"`) {
		t.Errorf("expected custom role 'system'")
	}
}

func TestEmitter_ToolCallStartArgsEndResult(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	tcID := emitter.ToolCallStart("search", "", "")
	if tcID == "" {
		t.Error("expected auto-generated tool call ID")
	}
	if !strings.Contains(chunks[0], "TOOL_CALL_START") {
		t.Errorf("expected TOOL_CALL_START event")
	}
	if !strings.Contains(chunks[0], `"search"`) {
		t.Errorf("expected tool call name")
	}

	emitter.ToolCallArgs(`{"query":"test"}`, "")
	if !strings.Contains(chunks[1], "TOOL_CALL_ARGS") {
		t.Errorf("expected TOOL_CALL_ARGS event")
	}

	emitter.ToolCallEnd("")
	if !strings.Contains(chunks[2], "TOOL_CALL_END") {
		t.Errorf("expected TOOL_CALL_END event")
	}

	// Start a new tool call to test ToolCallResult
	tcID2 := emitter.ToolCallStart("fetch", "tc-custom", "")
	if tcID2 != "tc-custom" {
		t.Errorf("expected custom tool call ID, got %s", tcID2)
	}

	emitter.ToolCallResult("done", "")
	if !strings.Contains(chunks[4], "TOOL_CALL_RESULT") {
		t.Errorf("expected TOOL_CALL_RESULT event")
	}
	if !strings.Contains(chunks[4], `"done"`) {
		t.Errorf("expected result value")
	}
}

func TestEmitter_ToolCallStartWithParentMessage(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.ToolCallStart("search", "tc-1", "msg-parent")
	if !strings.Contains(chunks[0], "msg-parent") {
		t.Errorf("expected parentMessageId in event")
	}
}

func TestEmitter_ToolCallArgsPanicsWithoutStart(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic when calling ToolCallArgs without ToolCallStart")
		}
	}()
	emitter.ToolCallArgs(`{}`, "")
}

func TestEmitter_ToolCallEndPanicsWithoutStart(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic")
		}
	}()
	emitter.ToolCallEnd("")
}

func TestEmitter_ToolCallResultPanicsWithoutStart(t *testing.T) {
	emitter := CreateAgUiEmitter(func(chunk string) {}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic")
		}
	}()
	emitter.ToolCallResult("result", "")
}

func TestEmitter_StateSnapshot(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.StateSnapshot(map[string]interface{}{"count": 42})
	if !strings.Contains(chunks[0], "STATE_SNAPSHOT") {
		t.Errorf("expected STATE_SNAPSHOT event")
	}
	if !strings.Contains(chunks[0], "42") {
		t.Errorf("expected snapshot data")
	}
}

func TestEmitter_StateDelta(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.StateDelta([]interface{}{
		map[string]interface{}{"op": "replace", "path": "/count", "value": 43},
	})
	if !strings.Contains(chunks[0], "STATE_DELTA") {
		t.Errorf("expected STATE_DELTA event")
	}
	if !strings.Contains(chunks[0], "replace") {
		t.Errorf("expected delta operation data")
	}
}

func TestEmitter_Custom(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.Custom("heartbeat", map[string]interface{}{"ts": 1234})
	if !strings.Contains(chunks[0], "CUSTOM") {
		t.Errorf("expected CUSTOM event")
	}
	if !strings.Contains(chunks[0], "heartbeat") {
		t.Errorf("expected custom event name")
	}
	if !strings.Contains(chunks[0], "1234") {
		t.Errorf("expected custom event value")
	}
}

func TestEmitter_EmitAddsTimestamp(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.Emit(AgUiEvent{"type": "TEST"})
	if !strings.Contains(chunks[0], `"timestamp"`) {
		t.Errorf("expected timestamp to be auto-added")
	}
}

func TestEmitter_EmitPreservesExistingTimestamp(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.Emit(AgUiEvent{"type": "TEST", "timestamp": int64(9999)})
	if !strings.Contains(chunks[0], "9999") {
		t.Errorf("expected existing timestamp to be preserved")
	}
}

func TestEmitter_StepStartedFinished(t *testing.T) {
	var chunks []string
	emitter := CreateAgUiEmitter(func(chunk string) {
		chunks = append(chunks, chunk)
	}, AgUiEmitterOptions{ThreadID: "t-1", RunID: "r-1"})

	emitter.StepStarted("planning")
	if !strings.Contains(chunks[0], "STEP_STARTED") {
		t.Errorf("expected STEP_STARTED")
	}
	if !strings.Contains(chunks[0], "planning") {
		t.Errorf("expected step name")
	}

	emitter.StepFinished("planning")
	if !strings.Contains(chunks[1], "STEP_FINISHED") {
		t.Errorf("expected STEP_FINISHED")
	}
}

func TestAgUiHeaders(t *testing.T) {
	if AgUiHeaders["Content-Type"] != "text/event-stream" {
		t.Errorf("expected Content-Type text/event-stream")
	}
	if AgUiHeaders["Cache-Control"] != "no-cache, no-transform" {
		t.Errorf("expected Cache-Control no-cache, no-transform")
	}
}
